name: ems

services:
  ems:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ems:3.12
    container_name: ems
    env_file:
      - path: .env
        required: false
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://192.168.0.34:5000}
    volumes:
      - .:/workspace
      - ems_pip_cache:/root/.cache/pip
    working_dir: /workspace
    command: sleep infinity

volumes:
  ems_pip_cache:
