name: cms

services:
  cms:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: cms:3.12
    container_name: cms
    env_file:
      - path: .env
        required: false
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://192.168.0.34:5000}
    volumes:
      - .:/workspace
      - cms_pip_cache:/root/.cache/pip
    working_dir: /workspace
    command: sleep infinity

volumes:
  cms_pip_cache:
