from src.forecasting.import_pmax.operations import (
    ARCHIVES_ROOT,
    CANDIDATES_ROOT,
    DEPLOYED_ROOT,
    INCOMING_ROOT,
    PROJECT_ROOT,
    TRAINING_JOBS_ROOT,
)


CANDIDATE_DIR = CANDIDATES_ROOT
ARCHIVES_DIR = ARCHIVES_ROOT
INCOMING_DIR = INCOMING_ROOT
TRAINING_JOBS_DIR = TRAINING_JOBS_ROOT
